import assert from "node:assert/strict";
import test from "node:test";
import { buildPayUTransferPayload, canRetryPayUStatus, isMerchantReferenceValid, isPayUPaymentType, mapPayUTransferStatus, resolvePaymentType } from "../lib/payu-payout-rules";

test("accepts UPI payment type", () => assert.equal(isPayUPaymentType("UPI"), true));
test("accepts IMPS payment type", () => assert.equal(isPayUPaymentType("IMPS"), true));
test("accepts NEFT payment type", () => assert.equal(isPayUPaymentType("NEFT"), true));
test("accepts RTGS payment type", () => assert.equal(isPayUPaymentType("RTGS"), true));
test("rejects arbitrary payment type", () => assert.equal(isPayUPaymentType("CHEQUE"), false));
test("rejects lowercase payment type without normalization", () => assert.equal(isPayUPaymentType("imps"), false));
test("UPI destination resolves to UPI", () => assert.equal(resolvePaymentType("UPI", "UPI"), "UPI"));
test("bank destination defaults to IMPS", () => assert.equal(resolvePaymentType("BANK_ACCOUNT", undefined), "IMPS"));
test("bank destination accepts NEFT", () => assert.equal(resolvePaymentType("BANK_ACCOUNT", "NEFT"), "NEFT"));
test("bank destination accepts RTGS", () => assert.equal(resolvePaymentType("BANK_ACCOUNT", "RTGS"), "RTGS"));
test("UPI cannot use IMPS", () => assert.throws(() => resolvePaymentType("UPI", "IMPS")));
test("UPI cannot use NEFT", () => assert.throws(() => resolvePaymentType("UPI", "NEFT")));
test("UPI cannot use RTGS", () => assert.throws(() => resolvePaymentType("UPI", "RTGS")));
test("bank destination cannot use UPI", () => assert.throws(() => resolvePaymentType("BANK_ACCOUNT", "UPI")));
test("invalid requested payment type throws", () => assert.throws(() => resolvePaymentType("BANK_ACCOUNT", "WALLET")));
test("PayU SUCCESS maps to SUCCESS", () => assert.equal(mapPayUTransferStatus("SUCCESS"), "SUCCESS"));
test("PayU FAILED maps to FAILED", () => assert.equal(mapPayUTransferStatus("FAILED"), "FAILED"));
test("PayU IN_PROGRESS maps to PROCESSING", () => assert.equal(mapPayUTransferStatus("IN_PROGRESS"), "PROCESSING"));
test("PayU PENDING maps to PROCESSING", () => assert.equal(mapPayUTransferStatus("PENDING"), "PROCESSING"));
test("PayU QUEUED maps to PROCESSING", () => assert.equal(mapPayUTransferStatus("QUEUED"), "PROCESSING"));
test("PayU WAITING_FOR_RETRY maps to PROCESSING", () => assert.equal(mapPayUTransferStatus("WAITING_FOR_RETRY"), "PROCESSING"));
test("unknown PayU status maps to UNKNOWN", () => assert.equal(mapPayUTransferStatus("SOMETHING_NEW"), "UNKNOWN"));
test("retry is allowed after definitive failure", () => assert.equal(canRetryPayUStatus("FAILED"), true));
test("retry is not allowed during processing", () => assert.equal(canRetryPayUStatus("PROCESSING"), false));
test("retry is not allowed for success", () => assert.equal(canRetryPayUStatus("SUCCESS"), false));
test("merchant reference accepts 40 characters", () => assert.equal(isMerchantReferenceValid("A".repeat(40)), true));
test("merchant reference rejects 41 characters", () => assert.equal(isMerchantReferenceValid("A".repeat(41)), false));
test("merchant reference accepts safe separators", () => assert.equal(isMerchantReferenceValid("PL-ABC_123.X"), true));
test("merchant reference rejects spaces", () => assert.equal(isMerchantReferenceValid("PL ABC"), false));
test("merchant reference rejects symbols outside PayU-safe set", () => assert.equal(isMerchantReferenceValid("PL/ABC"), false));
test("UPI payload contains UPI mode", () => assert.equal(buildPayUTransferPayload({ destinationType: "UPI", paymentType: "UPI", beneficiaryName: "Player", vpa: "player@upi", amount: "10.00", batchId: "batch", merchantRefId: "PL123" }).paymentType, "UPI"));
test("UPI payload contains VPA", () => assert.equal("vpa" in buildPayUTransferPayload({ destinationType: "UPI", paymentType: "UPI", beneficiaryName: "Player", vpa: "player@upi", amount: "10.00", batchId: "batch", merchantRefId: "PL124" }), true));
test("UPI payload excludes bank account field", () => assert.equal("beneficiaryAccountNumber" in buildPayUTransferPayload({ destinationType: "UPI", paymentType: "UPI", beneficiaryName: "Player", vpa: "player@upi", amount: "10.00", batchId: "batch", merchantRefId: "PL125" }), false));
test("bank payload contains account number", () => assert.equal("beneficiaryAccountNumber" in buildPayUTransferPayload({ destinationType: "BANK_ACCOUNT", paymentType: "IMPS", beneficiaryName: "Player", accountNumber: "1234567890", ifsc: "ABCD0123456", amount: "10.00", batchId: "batch", merchantRefId: "PL126" }), true));
test("bank payload contains IFSC", () => assert.equal("beneficiaryIfscCode" in buildPayUTransferPayload({ destinationType: "BANK_ACCOUNT", paymentType: "NEFT", beneficiaryName: "Player", accountNumber: "1234567890", ifsc: "ABCD0123456", amount: "10.00", batchId: "batch", merchantRefId: "PL127" }), true));
test("bank payload rejects missing account number", () => assert.throws(() => buildPayUTransferPayload({ destinationType: "BANK_ACCOUNT", paymentType: "IMPS", beneficiaryName: "Player", ifsc: "ABCD0123456", amount: "10.00", batchId: "batch", merchantRefId: "PL128" })));
test("bank payload rejects missing IFSC", () => assert.throws(() => buildPayUTransferPayload({ destinationType: "BANK_ACCOUNT", paymentType: "IMPS", beneficiaryName: "Player", accountNumber: "1234567890", amount: "10.00", batchId: "batch", merchantRefId: "PL129" })));
test("UPI payload rejects missing VPA", () => assert.throws(() => buildPayUTransferPayload({ destinationType: "UPI", paymentType: "UPI", beneficiaryName: "Player", amount: "10.00", batchId: "batch", merchantRefId: "PL130" })));
test("payload rejects invalid merchant reference", () => assert.throws(() => buildPayUTransferPayload({ destinationType: "UPI", paymentType: "UPI", beneficiaryName: "Player", vpa: "player@upi", amount: "10.00", batchId: "batch", merchantRefId: "bad ref" })));
test("payload rejects negative amount", () => assert.throws(() => buildPayUTransferPayload({ destinationType: "UPI", paymentType: "UPI", beneficiaryName: "Player", vpa: "player@upi", amount: "-1.00", batchId: "batch", merchantRefId: "PL131" })));
test("payload rejects zero amount", () => assert.throws(() => buildPayUTransferPayload({ destinationType: "UPI", paymentType: "UPI", beneficiaryName: "Player", vpa: "player@upi", amount: "0.00", batchId: "batch", merchantRefId: "PL132" })));
test("payload rejects more than two decimals", () => assert.throws(() => buildPayUTransferPayload({ destinationType: "UPI", paymentType: "UPI", beneficiaryName: "Player", vpa: "player@upi", amount: "10.001", batchId: "batch", merchantRefId: "PL133" })));
test("payload uses exact cents as numeric amount", () => assert.equal(buildPayUTransferPayload({ destinationType: "UPI", paymentType: "UPI", beneficiaryName: "Player", vpa: "player@upi", amount: "1234.50", batchId: "batch", merchantRefId: "PL134" }).amount, 1234.5));
test("payload always disables provider retry", () => assert.equal(buildPayUTransferPayload({ destinationType: "UPI", paymentType: "UPI", beneficiaryName: "Player", vpa: "player@upi", amount: "10.00", batchId: "batch", merchantRefId: "PL135" }).retry, false));
test("payload contains merchant reference", () => assert.equal(buildPayUTransferPayload({ destinationType: "UPI", paymentType: "UPI", beneficiaryName: "Player", vpa: "player@upi", amount: "10.00", batchId: "batch", merchantRefId: "PL136" }).merchantRefId, "PL136"));
test("payload contains batch ID", () => assert.equal(buildPayUTransferPayload({ destinationType: "UPI", paymentType: "UPI", beneficiaryName: "Player", vpa: "player@upi", amount: "10.00", batchId: "batch-1", merchantRefId: "PL137" }).batchId, "batch-1"));
test("payload keeps beneficiary email when supplied", () => assert.equal(buildPayUTransferPayload({ destinationType: "UPI", paymentType: "UPI", beneficiaryName: "Player", beneficiaryEmail: "player@example.com", vpa: "player@upi", amount: "10.00", batchId: "batch", merchantRefId: "PL138" }).beneficiaryEmail, "player@example.com"));
test("payload keeps beneficiary mobile when supplied", () => assert.equal(buildPayUTransferPayload({ destinationType: "UPI", paymentType: "UPI", beneficiaryName: "Player", beneficiaryMobile: "9876543210", vpa: "player@upi", amount: "10.00", batchId: "batch", merchantRefId: "PL139" }).beneficiaryMobile, "9876543210"));
test("bank payload supports IMPS", () => assert.equal(buildPayUTransferPayload({ destinationType: "BANK_ACCOUNT", paymentType: "IMPS", beneficiaryName: "Player", accountNumber: "1234567890", ifsc: "ABCD0123456", amount: "10.00", batchId: "batch", merchantRefId: "PL140" }).paymentType, "IMPS"));
test("bank payload supports NEFT", () => assert.equal(buildPayUTransferPayload({ destinationType: "BANK_ACCOUNT", paymentType: "NEFT", beneficiaryName: "Player", accountNumber: "1234567890", ifsc: "ABCD0123456", amount: "10.00", batchId: "batch", merchantRefId: "PL141" }).paymentType, "NEFT"));
test("bank payload supports RTGS", () => assert.equal(buildPayUTransferPayload({ destinationType: "BANK_ACCOUNT", paymentType: "RTGS", beneficiaryName: "Player", accountNumber: "1234567890", ifsc: "ABCD0123456", amount: "10.00", batchId: "batch", merchantRefId: "PL142" }).paymentType, "RTGS"));
