import { test } from "node:test";
import assert from "node:assert/strict";
import { isValidPayUPaymentType, isPaymentTypeAllowed, isValidMerchantReference, canRetryPayUPayout, isActivePayUPayout, isFinalPayUPayout, isKnownPayUWebhookEvent, mapsPayUTransferStatus, shouldReleaseReservation, shouldDebitWallet, isDefinitiveFailure, isAmbiguousProviderResult } from "@/lib/payu-payout-rules";

const expect = (actual: unknown) => ({
  toBe(expected: unknown) {
    assert.strictEqual(actual, expected);
  },
});

test("accepts UPI payment type", () => expect(isValidPayUPaymentType("UPI")).toBe(true));
test("accepts IMPS payment type", () => expect(isValidPayUPaymentType("IMPS")).toBe(true));
test("accepts NEFT payment type", () => expect(isValidPayUPaymentType("NEFT")).toBe(true));
test("accepts RTGS payment type", () => expect(isValidPayUPaymentType("RTGS")).toBe(true));
test("rejects arbitrary payment type", () => expect(isValidPayUPaymentType("FREEFORM")).toBe(false));
test("UPI destination only allows UPI", () => expect(isPaymentTypeAllowed("UPI", "UPI")).toBe(true));
test("UPI destination rejects IMPS", () => expect(isPaymentTypeAllowed("UPI", "IMPS")).toBe(false));
test("bank destination allows IMPS", () => expect(isPaymentTypeAllowed("BANK_ACCOUNT", "IMPS")).toBe(true));
test("bank destination allows NEFT", () => expect(isPaymentTypeAllowed("BANK_ACCOUNT", "NEFT")).toBe(true));
test("bank destination allows RTGS", () => expect(isPaymentTypeAllowed("BANK_ACCOUNT", "RTGS")).toBe(true));
test("bank destination rejects UPI", () => expect(isPaymentTypeAllowed("BANK_ACCOUNT", "UPI")).toBe(false));
test("merchant reference accepts alphanumeric", () => expect(isValidMerchantReference("PLabc123")).toBe(true));
test("merchant reference accepts underscore", () => expect(isValidMerchantReference("PLabc_123")).toBe(true));
test("merchant reference accepts hyphen", () => expect(isValidMerchantReference("PLabc-123")).toBe(true));
test("merchant reference rejects spaces", () => expect(isValidMerchantReference("PLabc 123")).toBe(false));
test("merchant reference rejects punctuation", () => expect(isValidMerchantReference("PLabc/123")).toBe(false));
test("merchant reference rejects over forty characters", () => expect(isValidMerchantReference("a".repeat(41))).toBe(false));
test("merchant reference accepts forty characters", () => expect(isValidMerchantReference("a".repeat(40))).toBe(true));
test("failed payout can retry", () => expect(canRetryPayUPayout("FAILED")).toBe(true));
test("processing payout cannot retry", () => expect(canRetryPayUPayout("PROCESSING")).toBe(false));
test("initiated payout cannot retry", () => expect(canRetryPayUPayout("PAYOUT_INITIATED")).toBe(false));
test("paid payout cannot retry", () => expect(canRetryPayUPayout("PAID")).toBe(false));
test("reversed payout cannot retry", () => expect(canRetryPayUPayout("REVERSED")).toBe(false));
test("initiated payout is active", () => expect(isActivePayUPayout("PAYOUT_INITIATED")).toBe(true));
test("processing payout is active", () => expect(isActivePayUPayout("PROCESSING")).toBe(true));
test("paid payout is final", () => expect(isFinalPayUPayout("PAID")).toBe(true));
test("failed payout is final", () => expect(isFinalPayUPayout("FAILED")).toBe(true));
test("reversed payout is final", () => expect(isFinalPayUPayout("REVERSED")).toBe(true));
test("success webhook is known", () => expect(isKnownPayUWebhookEvent("TRANSFER_SUCCESS")).toBe(true));
test("failed webhook is known", () => expect(isKnownPayUWebhookEvent("TRANSFER_FAILED")).toBe(true));
test("reversed webhook is known", () => expect(isKnownPayUWebhookEvent("TRANSFER_REVERSED")).toBe(true));
test("processing-failed webhook is known", () => expect(isKnownPayUWebhookEvent("REQUEST_PROCESSING_FAILED")).toBe(true));
test("unknown webhook is rejected", () => expect(isKnownPayUWebhookEvent("RANDOM_EVENT")).toBe(false));
test("PayU success maps to success", () => expect(mapsPayUTransferStatus("SUCCESS")).toBe("SUCCESS"));
test("PayU failed maps to failure", () => expect(mapsPayUTransferStatus("FAILED")).toBe("FAILED"));
test("PayU queued maps to processing", () => expect(mapsPayUTransferStatus("QUEUED")).toBe("PROCESSING"));
test("PayU pending maps to processing", () => expect(mapsPayUTransferStatus("PENDING")).toBe("PROCESSING"));
test("failed status releases reservation", () => expect(shouldReleaseReservation("FAILED")).toBe(true));
test("rejected status releases reservation", () => expect(shouldReleaseReservation("REJECTED")).toBe(true));
test("cancelled status releases reservation", () => expect(shouldReleaseReservation("CANCELLED")).toBe(true));
test("processing status does not release reservation", () => expect(shouldReleaseReservation("PROCESSING")).toBe(false));
test("paid status creates permanent debit", () => expect(shouldDebitWallet("PAID")).toBe(true));
test("processing status does not create debit", () => expect(shouldDebitWallet("PROCESSING")).toBe(false));
test("failed provider status is definitive failure", () => expect(isDefinitiveFailure("FAILED")).toBe(true));
test("timeout is ambiguous", () => expect(isAmbiguousProviderResult("TIMEOUT")).toBe(true));
test("5xx is ambiguous", () => expect(isAmbiguousProviderResult("HTTP_5XX")).toBe(true));
test("unknown result is ambiguous", () => expect(isAmbiguousProviderResult("UNKNOWN")).toBe(true));
test("malformed result is ambiguous", () => expect(isAmbiguousProviderResult("MALFORMED")).toBe(true));
test("definitive failure is not ambiguous", () => expect(isAmbiguousProviderResult("FAILED")).toBe(false));
test("final paid state is not active", () => expect(isActivePayUPayout("PAID")).toBe(false));
test("final failed state is not active", () => expect(isActivePayUPayout("FAILED")).toBe(false));
test("final reversed state is not active", () => expect(isActivePayUPayout("REVERSED")).toBe(false));
test("pending transfer is not final", () => expect(isFinalPayUPayout("PROCESSING")).toBe(false));
test("request processing failed is not treated as transfer failure", () => expect(mapsPayUTransferStatus("REQUEST_PROCESSING_FAILED")).toBe("PROCESSING"));
test("blank payment type is rejected", () => expect(isValidPayUPaymentType("")).toBe(false));
test("lowercase payment type is rejected by strict server rule", () => expect(isValidPayUPaymentType("upi")).toBe(false));
