import Link from "next/link";
import { SectionContainer } from "@/components/ui/section-container";
import { getAdminWalletDirectory } from "@/lib/admin-finance-tools";

export default async function AdminWalletsPage({ searchParams }: { searchParams: Promise<{ page?: string; query?: string; status?: string }> }) {
  const params = await searchParams;
  const page = Number(params.page ?? "1");
  const data = await getAdminWalletDirectory({ page, query: params.query, status: params.status });
  const href = (next: number) => `/admin/finance/wallets?${new URLSearchParams({ ...(params.query ? { query: params.query } : {}), ...(params.status ? { status: params.status } : {}), page: String(next) })}`;
  return <SectionContainer className="py-10 sm:py-14">
    <Link href="/admin/finance" className="text-sm font-semibold text-lime-300">← Finance</Link>
    <div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-lime-300">Finance</p><h1 className="mt-2 text-3xl font-black text-white sm:text-4xl">Wallet & user inspection</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Search users by ID, name, email or phone, then inspect their recorded balance and immutable-style ledger.</p></div><Link href="/admin/finance/adjustments" className="rounded-xl border border-amber-300/20 px-4 py-2 text-sm font-bold text-amber-100">Controlled adjustment</Link></div>
    <form method="get" className="mt-6 grid gap-3 rounded-2xl border border-white/10 bg-white/[0.025] p-4 sm:grid-cols-[1fr_180px_auto]"><input name="query" defaultValue={params.query ?? ""} placeholder="User ID, name, email or phone" className="min-h-11 rounded-xl border border-white/10 bg-slate-950/70 px-3 text-sm text-white outline-none" /><select name="status" defaultValue={params.status ?? ""} className="min-h-11 rounded-xl border border-white/10 bg-slate-950/70 px-3 text-sm text-white"><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option><option value="BANNED">Banned</option></select><button className="min-h-11 rounded-xl bg-lime-300 px-5 text-sm font-bold text-slate-950">Search users</button></form>
    <section className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.025]"><div className="border-b border-white/5 px-5 py-4 text-sm text-slate-400">{data.total} wallet{data.total === 1 ? "" : "s"} · page {data.page} of {data.totalPages}</div>{data.items.length === 0 ? <p className="p-10 text-center text-sm text-slate-500">No wallets match this search.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="text-xs uppercase tracking-wide text-slate-600"><tr><th className="px-5 py-3">User</th><th className="px-5 py-3">Role/status</th><th className="px-5 py-3">Balance</th><th className="px-5 py-3">Wallet</th><th className="px-5 py-3">Action</th></tr></thead><tbody>{data.items.map(w => <tr key={w.id} className="border-t border-white/5"><td className="px-5 py-4"><p className="font-bold text-white">{w.user.name || "Unnamed"}</p><p className="text-xs text-slate-500">{w.user.email}</p><p className="mt-1 font-mono text-[10px] text-slate-600">{w.userId}</p></td><td className="px-5 py-4 text-xs text-slate-400">{w.user.role} · {w.user.status}</td><td className="px-5 py-4 font-black text-white">₹{w.balance.toFixed(2)} {w.currency}</td><td className="px-5 py-4 font-mono text-[10px] text-slate-600">{w.id}</td><td className="px-5 py-4"><Link href={`/admin/finance/wallets/${w.id}`} className="font-semibold text-lime-300">View ledger →</Link></td></tr>)}</tbody></table></div>}{data.totalPages > 1 ? <nav className="flex items-center justify-between border-t border-white/5 px-5 py-4"><Link href={href(Math.max(1, data.page - 1))} className={data.page <= 1 ? "pointer-events-none text-slate-700" : "text-sm font-semibold text-lime-300"}>← Previous</Link><span className="text-xs text-slate-500">Page {data.page} of {data.totalPages}</span><Link href={href(Math.min(data.totalPages, data.page + 1))} className={data.page >= data.totalPages ? "pointer-events-none text-slate-700" : "text-sm font-semibold text-lime-300"}>Next →</Link></nav> : null}</section>
  </SectionContainer>;
}
