import Link from "next/link";
import { notFound } from "next/navigation";
import { SectionContainer } from "@/components/ui/section-container";
import { getAdminWallets } from "@/lib/wallet";

export default async function AdminWalletsPage({ searchParams }: { searchParams: Promise<{ page?: string }> }) {
  const params = await searchParams;
  const page = Number(params.page ?? "1");
  if (!Number.isSafeInteger(page) || page < 1) notFound();
  const { wallets, total, totalPages } = await getAdminWallets(page);
  return <SectionContainer className="py-10 sm:py-14">
    <Link href="/admin" className="text-sm font-semibold text-lime-300 hover:text-lime-200">← Admin</Link>
    <div className="mt-5"><p className="text-xs font-bold uppercase tracking-[0.2em] text-lime-300">Finance</p><h1 className="mt-2 text-3xl font-black text-white sm:text-4xl">Wallet reconciliation</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Read-only inspection of recorded wallet balances against the immutable-style ledger. No balance editing is available.</p></div>
    <section className="mt-8 rounded-2xl border border-white/10 bg-white/[0.025] p-5 sm:p-7"><p className="text-sm text-slate-500">{total} wallet{total === 1 ? "" : "s"} in the system.</p>{wallets.length === 0 ? <p className="mt-6 text-sm text-slate-500">No wallets have been created yet.</p> : <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="text-xs uppercase tracking-wide text-slate-600"><tr><th className="px-3 py-3">User</th><th className="px-3 py-3">Currency</th><th className="px-3 py-3">Recorded</th><th className="px-3 py-3">Calculated</th><th className="px-3 py-3">Difference</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Action</th></tr></thead><tbody>{wallets.map((wallet) => <tr key={wallet.id} className="border-t border-white/5"><td className="px-3 py-4"><p className="font-bold text-white">{wallet.user.name || "Unnamed"}</p><p className="text-xs text-slate-500">{wallet.user.email} · {wallet.user.status}</p></td><td className="px-3 py-4 text-slate-300">{wallet.currency}</td><td className="px-3 py-4 font-semibold text-white">₹{wallet.balance.toFixed(2)}</td><td className="px-3 py-4 text-slate-300">₹{wallet.reconciliation.expectedBalance}</td><td className={`px-3 py-4 font-bold ${wallet.reconciliation.difference === "0.00" ? "text-lime-200" : "text-rose-200"}`}>{wallet.reconciliation.difference === "0.00" ? "₹0.00" : `₹${wallet.reconciliation.difference}`}</td><td className="px-3 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${wallet.reconciliation.status === "CONSISTENT" ? "bg-lime-300/10 text-lime-200" : "bg-rose-300/10 text-rose-200"}`}>{wallet.reconciliation.status}</span></td><td className="px-3 py-4"><Link href={`/admin/finance/wallets/${wallet.id}`} className="font-semibold text-lime-300 hover:text-lime-200">View ledger →</Link></td></tr>)}</tbody></table></div>}{totalPages > 1 ? <nav className="mt-6 flex items-center justify-between border-t border-white/5 pt-5"><Link className={page <= 1 ? "pointer-events-none text-slate-700" : "text-lime-300"} href={`/admin/finance/wallets?page=${page - 1}`}>← Previous</Link><span className="text-xs text-slate-500">Page {page} of {totalPages}</span><Link className={page >= totalPages ? "pointer-events-none text-slate-700" : "text-lime-300"} href={`/admin/finance/wallets?page=${page + 1}`}>Next →</Link></nav> : null}</section>
  </SectionContainer>;
}
