import Link from "next/link";
import { SectionContainer } from "@/components/ui/section-container";
import { getAdminAuditEvents } from "@/lib/admin-finance-tools";

function date(v: Date) { return new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(v); }

export default async function AdminFinanceAuditPage({ searchParams }: { searchParams: Promise<{ page?: string; action?: string; targetType?: string; query?: string }> }) {
  const p = await searchParams;
  const { page: rawPage, ...filters } = p;
  const data = await getAdminAuditEvents({ ...filters, page: rawPage ? Number(rawPage) : undefined });
  const href = (next: number) => `/admin/finance/audit?${new URLSearchParams({ ...(p.action ? { action: p.action } : {}), ...(p.targetType ? { targetType: p.targetType } : {}), ...(p.query ? { query: p.query } : {}), page: String(next) })}`;
  return <SectionContainer className="py-10 sm:py-14">
    <Link href="/admin/finance" className="text-sm font-semibold text-lime-300">← Finance</Link>
    <div className="mt-5"><p className="text-xs font-bold uppercase tracking-[0.2em] text-lime-300">Security & audit</p><h1 className="mt-2 text-3xl font-black text-white">Financial admin audit log</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Sensitive financial operations are recorded with actor, action, target, metadata and timestamp. Secrets and authentication tokens are never written here.</p></div>
    <form method="get" className="mt-6 grid gap-3 rounded-2xl border border-white/10 bg-white/[0.025] p-4 sm:grid-cols-3"><input name="query" defaultValue={p.query ?? ""} placeholder="Target ID or admin email" className="min-h-11 rounded-xl border border-white/10 bg-slate-950/70 px-3 text-sm text-white" /><input name="action" defaultValue={p.action ?? ""} placeholder="Action" className="min-h-11 rounded-xl border border-white/10 bg-slate-950/70 px-3 text-sm text-white" /><input name="targetType" defaultValue={p.targetType ?? ""} placeholder="Target type" className="min-h-11 rounded-xl border border-white/10 bg-slate-950/70 px-3 text-sm text-white" /><button className="min-h-11 rounded-xl bg-lime-300 px-4 text-sm font-bold text-slate-950 sm:col-span-3">Filter audit log</button></form>
    <section className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.025]"><div className="border-b border-white/5 px-5 py-4 text-sm text-slate-400">{data.total} audit event{data.total === 1 ? "" : "s"} · page {data.page} of {data.totalPages}</div>{data.items.length === 0 ? <p className="p-10 text-center text-sm text-slate-500">No audit events match the filters.</p> : <div className="divide-y divide-white/5">{data.items.map(x => <article key={x.id} className="grid gap-3 p-5 lg:grid-cols-[180px_1fr_1fr]"><div><p className="text-xs text-slate-500">{date(x.createdAt)}</p><p className="mt-1 text-sm font-semibold text-white">{x.actor.name || "Unnamed admin"}</p><p className="text-xs text-slate-500">{x.actor.email}</p></div><div><p className="font-bold text-lime-200">{x.action}</p><p className="mt-1 text-xs text-slate-500">{x.targetType} · {x.targetId}</p></div><pre className="overflow-auto rounded-xl border border-white/5 bg-black/20 p-3 text-[11px] leading-5 text-slate-400">{x.metadataJson || "No metadata"}</pre></article>)}</div>}{data.totalPages > 1 ? <nav className="flex items-center justify-between border-t border-white/5 px-5 py-4"><Link href={href(Math.max(1, data.page - 1))} className={data.page <= 1 ? "pointer-events-none text-slate-700" : "text-sm font-semibold text-lime-300"}>← Previous</Link><span className="text-xs text-slate-500">Page {data.page} of {data.totalPages}</span><Link href={href(Math.min(data.totalPages, data.page + 1))} className={data.page >= data.totalPages ? "pointer-events-none text-slate-700" : "text-sm font-semibold text-lime-300"}>Next →</Link></nav> : null}</section>
  </SectionContainer>;
}
